# Generated by Django 4.1 on 2022-08-29 11:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='user',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='user_profile'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
